{% include static/js/reconnecting-websocket.js %}
{% include static/js/wsInit.js %}
{% include static/js/wsSendMessage.js %}
{% include static/js/admin_wsOnMessage.js %}
{% include static/js/admin.js %}
{% include static/js/cookie.js %}
{% include static/js/time.js %}
{% include static/js/admin_queue.js %}
{% include static/js/admin_users.js %}
