<script type="text/javascript" src="/static/js/reconnecting-websocket.js"></script>
<script type="text/javascript" src="/static/js/wsInit.js"></script>
<script type="text/javascript" src="/static/js/wsSendMessage.js"></script>
<script type="text/javascript" src="/static/js/admin_wsOnMessage.js"></script>
<script type="text/javascript" src="/static/js/admin.js"></script>
<script type="text/javascript" src="/static/js/cookie.js"></script>
<script type="text/javascript" src="/static/js/time.js"></script>
<script type="text/javascript" src="/static/js/admin_queue.js"></script>
<script type="text/javascript" src="/static/js/admin_users.js"></script>
