<script type="text/javascript" src="/static/js/wsInit.js"></script>
<script type="text/javascript" src="/static/js/misc.js"></script>
<script type="text/javascript" src="/static/js/cookie.js"></script>
<script type="text/javascript" src="/static/js/time.js"></script>
<script type="text/javascript" src="/static/js/youtube.js"></script>
<script type="text/javascript" src="/static/js/chat.js"></script>
<script type="text/javascript" src="/static/js/opinion.js"></script>
<script type="text/javascript" src="/static/js/alert.js"></script>
<script type="text/javascript" src="/static/js/queue.js"></script>
<script type="text/javascript" src="/static/js/wsSendMessage.js"></script>
<script type="text/javascript" src="/static/js/wsOnMessage.js"></script>
<script type="text/javascript" src="/static/js/video.js"></script>
